INSERT INTO userinfo (name,task) VALUES ('ALICE', 'finish finals');
INSERT INTO userinfo (name,task) VALUES ('BEN', 'write report');
INSERT INTO userinfo (name,task) VALUES ('CHARLIE', 'reading');
INSERT INTO userinfo (name,task) VALUES ('DAN', 'review for the assessment');
INSERT INTO userinfo (name,task) VALUES ('JOHN', 'work out');
INSERT INTO userinfo (name,task) VALUES ('PETER', 'meeting');
INSERT INTO userinfo (name,task) VALUES ('MIKE', 'gorecery shopping');
INSERT INTO userinfo (name,task) VALUES ('CHRIS', 'check out the cars');
INSERT INTO userinfo (name,task) VALUES ('LUKE', 'house cleaning');
INSERT INTO userinfo (name,task) VALUES ('NICK', 'take kids outside play');
